cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$8TqZMN3vX8.UcyfMMtN7uuU1xdDup29HGarnjobzutYrhgh6RuOUC
    lsn:
      email: 49121953@qq.com
      name: Shunan Lu
      password: $2b$12$0OoqEj1uazomcO7HIXdUF.zGlPgaQl8UuYOwJ6uMN3d0sIKAzqZV.
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$oazXkLFD1O0ro9N.uKoOguc7axPhIblqNL82ypTdWcK008XN58pBC
preauthorized:
  emails:
  - melsby@gmail.com
